server {
    listen 443 ssl;
    server_name auth.__DOMAIN__;
    include /etc/nginx/snippets/tls.conf;
    location / {
        include /etc/nginx/snippets/proxy.conf;
        set $backend http://authelia:9091;
        proxy_pass $backend;
    }
}
