server {
    listen 443 ssl;
    server_name secure.__DOMAIN__;
    include /etc/nginx/snippets/tls.conf;
    include /etc/nginx/snippets/authelia-location.conf;
    location / {
        include /etc/nginx/snippets/proxy.conf;
        include /etc/nginx/snippets/authelia-authrequest.conf;
        set $backend http://demo:80;
        proxy_pass $backend;
    }
}
