#!/usr/bin/env python3
"""Create private runtime configuration without overwriting an existing setup."""
import argparse
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--domain', required=True, help='Parent domain, e.g. example.com')
    parser.add_argument('--email', required=True, help='Email for the initial admin user')
    args = parser.parse_args()
    domain = args.domain.lower()
    if len(domain) > 253 or not re.fullmatch(r'(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}', domain):
        parser.error('Use a valid parent DNS domain, without scheme, port, or path.')
    if '@' not in args.email or any(c.isspace() for c in args.email):
        parser.error('Use a valid email address.')
    if (ROOT / 'data').exists() or (ROOT / 'secrets').exists():
        parser.error('data/ or secrets/ already exists; edit the existing setup instead.')
    if not shutil.which('openssl'):
        parser.error('openssl is required to generate the bootstrap certificate.')
    password_hash = input('Paste the Authelia Argon2id password hash: ').strip()
    if not re.fullmatch(r'\$argon2id\$v=19\$m=\d+,t=\d+,p=\d+\$[A-Za-z0-9+/]+\$[A-Za-z0-9+/]+', password_hash):
        parser.error('Expected an Argon2id hash generated by Authelia.')
    os.umask(0o077)
    for name in ['nginx', 'nginx-ui', 'certs', 'www', 'authelia']:
        (ROOT / 'data' / name).mkdir(parents=True)
    for template in (ROOT / 'templates').rglob('*'):
        if template.is_file():
            target = ROOT / 'data' / template.relative_to(ROOT / 'templates')
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(template.read_text().replace('__DOMAIN__', domain))
    for name in ['conf.d', 'sites-enabled', 'streams-available', 'streams-enabled']:
        (ROOT / 'data/nginx' / name).mkdir()
    for site in (ROOT / 'data/nginx/sites-available').iterdir():
        (ROOT / 'data/nginx/sites-enabled' / site.name).symlink_to('../sites-available/' + site.name)
    # Workers need traversal/read access to static content and Nginx files.
    for path in (ROOT / 'data/nginx').rglob('*'):
        if not path.is_symlink():
            path.chmod(0o755 if path.is_dir() else 0o644)
    (ROOT / 'data/nginx').chmod(0o755)
    (ROOT / 'data/www').chmod(0o755)
    users = {'users': {'admin': {'displayname': 'Administrator', 'password': password_hash,
                               'email': args.email, 'groups': ['admins']}}}
    # JSON is valid YAML; encoding safely handles special characters.
    (ROOT / 'data/authelia/users_database.yml').write_text(json.dumps(users, indent=2) + '\n')
    (ROOT / 'secrets').mkdir()
    for name in ['session', 'storage', 'jwt']:
        (ROOT / 'secrets' / name).write_text(secrets.token_hex(64) + '\n')
    subprocess.run(['openssl', 'req', '-x509', '-nodes', '-newkey', 'rsa:3072',
                    '-days', '30', '-subj', '/CN=auth.' + domain,
                    '-addext', 'subjectAltName=DNS:auth.' + domain + ',DNS:secure.' + domain + ',DNS:public.' + domain,
                    '-keyout', str(ROOT / 'data/certs/privkey.pem'),
                    '-out', str(ROOT / 'data/certs/fullchain.pem')], check=True, capture_output=True)
    if not (ROOT / '.env').exists():
        shutil.copyfile(ROOT / '.env.example', ROOT / '.env')
    print('Setup created. Replace the bootstrap TLS certificate before production.')
    print('Next: docker compose config --quiet && docker compose up -d')

if __name__ == '__main__':
    main()
